/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.permission_group_id_seq</code>
     */
    public static final Sequence<Integer> PERMISSION_GROUP_ID_SEQ = new SequenceImpl<Integer>("permission_group_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_ID_SEQ = new SequenceImpl<Integer>("role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.role_permission_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_PERMISSION_ID_SEQ = new SequenceImpl<Integer>("role_permission_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
