/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db;


import com.example.possutest.db.tables.PermissionGroup;
import com.example.possutest.db.tables.Role;
import com.example.possutest.db.tables.RolePermission;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.permission_group</code>.
     */
    public static final PermissionGroup PERMISSION_GROUP = PermissionGroup.PERMISSION_GROUP;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = RolePermission.ROLE_PERMISSION;
}
