/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db.tables.daos;


import com.example.possutest.db.tables.PermissionGroup;
import com.example.possutest.db.tables.records.PermissionGroupRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionGroupDao extends DAOImpl<PermissionGroupRecord, com.example.possutest.db.tables.pojos.PermissionGroup, Integer> {

    /**
     * Create a new PermissionGroupDao without any configuration
     */
    public PermissionGroupDao() {
        super(PermissionGroup.PERMISSION_GROUP, com.example.possutest.db.tables.pojos.PermissionGroup.class);
    }

    /**
     * Create a new PermissionGroupDao with an attached configuration
     */
    public PermissionGroupDao(Configuration configuration) {
        super(PermissionGroup.PERMISSION_GROUP, com.example.possutest.db.tables.pojos.PermissionGroup.class, configuration);
    }

    @Override
    public Integer getId(com.example.possutest.db.tables.pojos.PermissionGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PermissionGroup.PERMISSION_GROUP.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchById(Integer... values) {
        return fetch(PermissionGroup.PERMISSION_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.possutest.db.tables.pojos.PermissionGroup fetchOneById(Integer value) {
        return fetchOne(PermissionGroup.PERMISSION_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PermissionGroup.PERMISSION_GROUP.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchByName(String... values) {
        return fetch(PermissionGroup.PERMISSION_GROUP.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchRangeOfParentId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PermissionGroup.PERMISSION_GROUP.PARENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.PermissionGroup> fetchByParentId(Integer... values) {
        return fetch(PermissionGroup.PERMISSION_GROUP.PARENT_ID, values);
    }
}
