/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db.tables.daos;


import com.example.possutest.db.tables.RolePermission;
import com.example.possutest.db.tables.records.RolePermissionRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionDao extends DAOImpl<RolePermissionRecord, com.example.possutest.db.tables.pojos.RolePermission, Integer> {

    /**
     * Create a new RolePermissionDao without any configuration
     */
    public RolePermissionDao() {
        super(RolePermission.ROLE_PERMISSION, com.example.possutest.db.tables.pojos.RolePermission.class);
    }

    /**
     * Create a new RolePermissionDao with an attached configuration
     */
    public RolePermissionDao(Configuration configuration) {
        super(RolePermission.ROLE_PERMISSION, com.example.possutest.db.tables.pojos.RolePermission.class, configuration);
    }

    @Override
    public Integer getId(com.example.possutest.db.tables.pojos.RolePermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(RolePermission.ROLE_PERMISSION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchById(Integer... values) {
        return fetch(RolePermission.ROLE_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.possutest.db.tables.pojos.RolePermission fetchOneById(Integer value) {
        return fetchOne(RolePermission.ROLE_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(RolePermission.ROLE_PERMISSION.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchByName(String... values) {
        return fetch(RolePermission.ROLE_PERMISSION.NAME, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchRangeOfRoleId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(RolePermission.ROLE_PERMISSION.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.example.possutest.db.tables.pojos.RolePermission> fetchByRoleId(Integer... values) {
        return fetch(RolePermission.ROLE_PERMISSION.ROLE_ID, values);
    }
}
