/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionGroup implements Serializable {

    private static final long serialVersionUID = 2130199329;

    private Integer id;
    private String  name;
    private Integer parentId;

    public PermissionGroup() {}

    public PermissionGroup(PermissionGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.parentId = value.parentId;
    }

    public PermissionGroup(
        Integer id,
        String  name,
        Integer parentId
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissionGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);

        sb.append(")");
        return sb.toString();
    }
}
