/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = -797199572;

    private Integer id;
    private String  name;
    private String  type;
    private Integer groupId;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.groupId = value.groupId;
    }

    public Role(
        Integer id,
        String  name,
        String  type,
        Integer groupId
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.groupId = groupId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(groupId);

        sb.append(")");
        return sb.toString();
    }
}
