/*
 * This file is generated by jOOQ.
 */
package com.example.possutest.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermission implements Serializable {

    private static final long serialVersionUID = -2068759671;

    private Integer id;
    private String  name;
    private Integer roleId;

    public RolePermission() {}

    public RolePermission(RolePermission value) {
        this.id = value.id;
        this.name = value.name;
        this.roleId = value.roleId;
    }

    public RolePermission(
        Integer id,
        String  name,
        Integer roleId
    ) {
        this.id = id;
        this.name = name;
        this.roleId = roleId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolePermission (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
